on: push
name: APK
jobs:
  apk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 22.0.1+8
      - uses: android-actions/setup-android@v3.2.1
        with:
          cmdline-tools-version: 11076708
          packages: ""
      - run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4.3.3
        with:
          path: composeApp/build/outputs/apk/debug/composeApp-debug.apk
          if-no-files-found: error
          compression-level: 0
          name: APK
