on: push
name: Cloudflare Pages
jobs:
  cloudflare-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17.0.11+9
      - run: |
          chmod +x gradlew
          ./gradlew wasmJsBrowserProductionWebpack --no-daemon
      - uses: cloudflare/wrangler-action@v3.5.0
        with:
          wranglerVersion: 3.57.0
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 9839aabb4253ed85d80549a8f99ee832
          command: >
            pages deploy composeApp/build/dist/wasmJs/productionExecutable --project-name=pawsitive
