on: push
name: Cloudflare Pages
jobs:
  cloudflare-pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 22.0.1+8
      - run: |
          chmod +x gradlew
          ./gradlew wasmJsBrowserDistribution
      - uses: cloudflare/wrangler-action@v3.6.1
        with:
          wranglerVersion: 3.57.1
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 9839aabb4253ed85d80549a8f99ee832
          command: >
            pages deploy composeApp/build/dist/wasmJs/productionExecutable --project-name=pawsitive
